image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_IMAGE: registry.gitlab.com/kien3361931/Test

stages:
  - build
  - test
  - push

before_script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .

test:
  stage: test
  script:
    - docker run -d --name flask_app_test $CI_REGISTRY_IMAGE:latest
    - docker exec flask_app_test pip install pytest
    - docker exec flask_app_test pytest
    - docker rm -f flask_app_test

push:
  stage: push
  script:
    - docker push $CI_REGISTRY_IMAGE:latest
